name: Crates

on: [release]

jobs:
  test:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - run: ~/.cargo/bin/rustup self update
    - run: ~/.cargo/bin/rustup update
    - run: ~/.cargo/bin/cargo build --verbose
    - run: ~/.cargo/bin/cargo test --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to crates.io
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - run: ~/.cargo/bin/rustup self update
    - run: ~/.cargo/bin/cargo publish
      # the GitHub Action "release" event is a little trickier than I thought
      if: >-
        github.event_name == 'release' &&
        (
          github.event.action == 'created' ||
          github.event.action == 'prereleased' ||
          github.event.action == 'published'
        ) &&
        !github.event.release.draft &&
        github.event.release.published_at
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

