name: Rust

on: [push]

jobs:
  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - run: source $HOME/.cargo/env
    - run: rustup self update
    - run: rustup update
    - run: rustup component add clippy
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo clippy --all-features --all-targets -- -D clippy::all


